feat: new `github-teams` script
zendeskgarden/scripts pull request #216
Opened 2024-06-24 18:52 UTC by jzempel

## Description

This PR adds a new `garden github-teams` CLI, corresponding `githubTeams` API, and supporting documentation. See the new README for details.

## Detail

To be used along with GH Actions conditionals for job security :wink:

2024-06-24 19:40 UTC, ze-flo approved these changes
Fantastic work! 💯 🔥 🚀

2024-06-24 19:40 UTC, ze-flo commented on src/github/teams/index.ts
> +    const org = (args.org || (await getRepository(args.path, args.spinner))?.owner)!;
`getRepository` handles a missing path. ✅

2024-06-24 20:43 UTC, geotrev requested changes
Just the tiny typo. Otherwise :shipit:

2024-06-24 21:12 UTC, jzempel commented on src/github/teams/index.ts
> +    .option('-u --user [user]', 'user to get team membership for; defaults to current')
Nice catch 😅

2024-06-25 18:09 UTC, geotrev approved these changes

2024-06-25 18:10 UTC, merged